functionsDirectory = "C:\\Users\\preet\\OneDrive\\Documents\\BudgetTools\\budgettools\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[build]
publish = "C:\\Users\\preet\\OneDrive\\Documents\\BudgetTools\\budgettools"
publishOrigin = "config"
functions = "C:\\Users\\preet\\OneDrive\\Documents\\BudgetTools\\budgettools\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]
node_bundler = "esbuild"

[[headers]]
for = "/*.html"

[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
for = "/js/*"

[headers.values]
Cache-Control = "public, max-age=86400"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/webhooks/cashfree"
to = "/.netlify/functions/payment-webhook"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/auth/callback"
to = "/auth.html?mode=callback"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]